# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      override:
        description: 'Version Number'
        required: true
        default: '0.0.0'
#on:
#  release:
#    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Deploy to GitHub
      run: mvn  --file demo/pom.xml --batch-mode -DuseGitHubPackages=true deploy 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
